<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Kikaria</RootNamespace>
    <AssemblyName>Kikaria</AssemblyName>
    <UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseXamlCompilerExecutable>false</UseXamlCompilerExecutable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240227000" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Presets\**\*.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Presets\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <!-- Override the UsingTask to use the .NET 6 version of the compiler task with explicit Runtime and Architecture -->
  <UsingTask TaskName="Microsoft.UI.Xaml.Markup.Compiler.Tasks.CompileXaml"
             AssemblyFile="$(NuGetPackageRoot)microsoft.windowsappsdk\1.5.240227000\tools\net6.0\Microsoft.UI.Xaml.Markup.Compiler.dll"
             Runtime="NET"
             Architecture="x64"
             Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk\1.5.240227000\tools\net6.0\Microsoft.UI.Xaml.Markup.Compiler.dll')" />
  
  <UsingTask TaskName="Microsoft.UI.Xaml.Markup.Compiler.IO.InputSerializer"
             AssemblyFile="$(NuGetPackageRoot)microsoft.windowsappsdk\1.5.240227000\tools\net6.0\Microsoft.UI.Xaml.Markup.Compiler.IO.dll"
             Runtime="NET"
             Architecture="x64"
             Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk\1.5.240227000\tools\net6.0\Microsoft.UI.Xaml.Markup.Compiler.IO.dll')" />
  
  <UsingTask TaskName="Microsoft.UI.Xaml.Markup.Compiler.IO.OutputDeserializer"
             AssemblyFile="$(NuGetPackageRoot)microsoft.windowsappsdk\1.5.240227000\tools\net6.0\Microsoft.UI.Xaml.Markup.Compiler.IO.dll"
             Runtime="NET"
             Architecture="x64"
             Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk\1.5.240227000\tools\net6.0\Microsoft.UI.Xaml.Markup.Compiler.IO.dll')" />
</Project>
