<Project>
  <Target Name="MarkupCompilePass1">
    <Message Text="Overriding MarkupCompilePass1 to do nothing" Importance="high"/>
    <ItemGroup>
      <FileWrites Include="$(IntermediateOutputPath)**\*.g.cs;$(IntermediateOutputPath)**\*.g.i.cs;$(IntermediateOutputPath)**\*.xbf"/>
    </ItemGroup>
  </Target>
  
  <Target Name="MarkupCompilePass2">
    <Message Text="Overriding MarkupCompilePass2 to do nothing" Importance="high"/>
  </Target>
  
  <Target Name="WinUICoreCompileXaml">
    <Message Text="Overriding WinUICoreCompileXaml to do nothing" Importance="high"/>
  </Target>
</Project>
