<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Intatis.Cli</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>intatis</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intatis.Core\Intatis.Core.csproj" />
  </ItemGroup>

</Project>
