<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Intatis.Windows.Shared</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>

